version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python noxchange_api.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MAIL_ADDRESS=noxchange.dev@gmail.com
      - MAIL_PWD=zuperSecur3!
      - SECRET=acbd18db4cc2f85cedef654fccc4a4d8
      - DB_URI=postgresql://postgres@db:5432/postgres
      - PORT=5000
      - LOCAL=True